In [37]:
import numpy as np
import torch
from torch.utils import data


def synthetic_data(w, b, num_examples):  #@save
    """生成y=Xw+b+噪声"""
    X = torch.normal(0, 1, (num_examples, len(w)))
    y = torch.matmul(X, w) + b
    y += torch.normal(0, 0.01, y.shape)
    return X, y.reshape(-1,1)


true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = synthetic_data(true_w, true_b, 1000)

In [38]:
def load_array(data_arrays, batch_size, is_train=True):  #@save
    """构造一个PyTorch数据迭代器"""
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [39]:
next(iter(data_iter))

[tensor([[ 0.5083,  0.4376],
         [-0.0185, -0.8593],
         [ 2.0000,  0.8390],
         [-0.4573, -1.9384],
         [ 1.5441, -0.5918],
         [-1.0802,  0.7494],
         [ 1.1974, -2.1598],
         [-1.5337, -0.8170],
         [ 0.9106, -1.5626],
         [-0.3860,  0.8525]]),
 tensor([[ 3.7384],
         [ 7.0910],
         [ 5.3651],
         [ 9.8657],
         [ 9.3012],
         [-0.5113],
         [13.9433],
         [ 3.9173],
         [11.3324],
         [ 0.5255]])]

In [40]:
# nn是神经网络的缩写
from torch import nn
net = nn.Sequential(nn.Linear(2, 1))

# 2 * 1 是权值矩阵，

In [41]:
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [42]:
loss = nn.MSELoss()

In [43]:
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

# 指定优化对象和学习率

In [54]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X) ,y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000105
epoch 2, loss 0.000106
epoch 3, loss 0.000104


# net(X) 就是将输入数据放入神经网络层计算,net即是容器又是函数

In [55]:
net(features)

tensor([[ 0.0230],
        [ 5.5838],
        [ 5.0813],
        [ 3.4480],
        [ 0.5976],
        [ 8.9810],
        [ 5.5049],
        [ 8.2361],
        [-0.4867],
        [ 4.1141],
        [ 7.6093],
        [ 6.7087],
        [ 1.1574],
        [ 2.9867],
        [ 7.5094],
        [-3.1240],
        [10.6944],
        [ 6.0467],
        [ 8.3488],
        [ 3.9265],
        [ 4.6867],
        [-3.1635],
        [-0.2961],
        [ 2.9462],
        [ 7.3111],
        [ 7.0851],
        [ 3.1671],
        [ 5.5930],
        [ 3.4051],
        [ 9.4173],
        [-4.5928],
        [ 7.8783],
        [ 1.8187],
        [-0.3411],
        [ 3.2759],
        [ 8.0822],
        [-1.2898],
        [ 7.8966],
        [ 0.8580],
        [ 4.7913],
        [ 4.7846],
        [ 9.8032],
        [ 2.2364],
        [ 2.6956],
        [ 0.9865],
        [ 2.5083],
        [12.0587],
        [ 3.0960],
        [11.9575],
        [ 7.8727],
        [14.1413],
        [ 2.4920],
        [10.

In [56]:
labels

tensor([[ 0.0278],
        [ 5.6007],
        [ 5.0809],
        [ 3.4289],
        [ 0.6098],
        [ 8.9645],
        [ 5.5191],
        [ 8.2307],
        [-0.4844],
        [ 4.1167],
        [ 7.6130],
        [ 6.7116],
        [ 1.1656],
        [ 2.9796],
        [ 7.4977],
        [-3.1155],
        [10.6781],
        [ 6.0267],
        [ 8.3516],
        [ 3.9408],
        [ 4.6781],
        [-3.1615],
        [-0.2749],
        [ 2.9435],
        [ 7.3196],
        [ 7.0942],
        [ 3.1530],
        [ 5.5864],
        [ 3.3970],
        [ 9.4252],
        [-4.5636],
        [ 7.8817],
        [ 1.8262],
        [-0.3496],
        [ 3.2842],
        [ 8.0777],
        [-1.2676],
        [ 7.9138],
        [ 0.8533],
        [ 4.8057],
        [ 4.7867],
        [ 9.8100],
        [ 2.2412],
        [ 2.7114],
        [ 0.9805],
        [ 2.4884],
        [12.0583],
        [ 3.0904],
        [11.9806],
        [ 7.8845],
        [14.1457],
        [ 2.5018],
        [10.

### w = net[0].weight.data
print('w的估计误差：', true_w - w.reshape(true_w.shape))
b = net[0].bias.data
print('b的估计误差：', true_b - b)